import "server-only";
import { Resend } from "resend";
import { createUnsubscribeToken } from "./unsubscribe";

export function getResend(){return process.env.RESEND_API_KEY?new Resend(process.env.RESEND_API_KEY):null}
const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
function unsubscribeUrl(userId:string){const origin=process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3000";return`${origin}/notificaciones/baja?token=${encodeURIComponent(createUnsubscribeToken(userId))}`}

export async function sendWelcomeEmail(input:{userId:string;email:string;name:string}){const resend=getResend();const from=process.env.RESEND_FROM_EMAIL;if(!resend||!from)return{configured:false};const link=unsubscribeUrl(input.userId);const{error}=await resend.emails.send({from,to:input.email,subject:"Bienvenido al Inner Circle",html:`<div style="font-family:Arial;background:#09070b;color:#fff;padding:32px"><h1>La señal está activa.</h1><p>Hola ${escape(input.name)}, tu perfil IAMJOSHWA / AFTERLUV está listo.</p><p>Recibirás únicamente los avisos que elegiste.</p><p style="margin-top:32px"><a href="${link}" style="color:#d88cff">Cambiar preferencias o cancelar suscripción</a></p></div>`,headers:{"List-Unsubscribe":`<${link}>`}});if(error)throw error;return{configured:true}}

export async function sendBookingEmails(input:{folio:string;name:string;email:string;project:string;eventDate:string;city:string}){const resend=getResend();const from=process.env.RESEND_FROM_EMAIL;const admin=process.env.BOOKING_NOTIFICATION_EMAIL;if(!resend||!from)return{configured:false};const origin=process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3000";const epk=`${origin}/epk`;const adminUrl=`${origin}/admin/booking`;const project=escape(input.project.toUpperCase());const subject=`Solicitud de booking recibida — ${input.folio}`;await resend.emails.send({from,to:input.email,subject,html:`<div style="margin:0;background:#050505;color:#fff;font-family:Arial,Helvetica,sans-serif;padding:36px"><div style="max-width:680px;margin:auto;border:1px solid rgba(255,255,255,.14);border-radius:24px;background:linear-gradient(145deg,#151018,#08070a);padding:32px"><p style="color:#d88cff;letter-spacing:.18em;font-size:11px;text-transform:uppercase">Booking request</p><h1 style="font-size:40px;line-height:.95;margin:12px 0">Recibimos tu solicitud.</h1><p style="color:#c8c0d2;line-height:1.6">Hola ${escape(input.name)}, gracias por considerar a ${project}. Revisaremos la información de forma humana y responderemos normalmente dentro de 24–48 horas hábiles.</p><div style="margin:26px 0;padding:20px;border-radius:18px;background:#fff;color:#050505"><span style="display:block;font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:#6f35ff">Folio de seguimiento</span><strong style="font-size:30px">${escape(input.folio)}</strong></div><p style="color:#c8c0d2"><strong style="color:white">Proyecto:</strong> ${project}<br/><strong style="color:white">Ciudad:</strong> ${escape(input.city)}<br/><strong style="color:white">Fecha:</strong> ${escape(input.eventDate)}</p><p style="margin-top:28px"><a href="${epk}" style="display:inline-block;background:#d88cff;color:#050505;text-decoration:none;border-radius:999px;padding:13px 18px;font-weight:bold">Ver EPK oficial</a></p><p style="font-size:12px;color:#8f8797;margin-top:28px">Guarda este folio para cualquier seguimiento. Esta confirmación no representa una cotización definitiva.</p></div></div>`});if(admin)await resend.emails.send({from,to:admin,subject:`Nueva solicitud ${input.folio}`,html:`<div style="font-family:Arial,Helvetica,sans-serif"><h2>Nueva solicitud de booking</h2><p><strong>Folio:</strong> ${escape(input.folio)}</p><p>${escape(input.name)} solicita ${project} en ${escape(input.city)} para ${escape(input.eventDate)}.</p><p><a href="${adminUrl}">Abrir panel de booking</a></p></div>`});return{configured:true}}
