import "server-only";
import { Resend } from "resend";
import { createUnsubscribeToken } from "./unsubscribe";

export function getResend(){return process.env.RESEND_API_KEY?new Resend(process.env.RESEND_API_KEY):null}
const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
function unsubscribeUrl(userId:string){const origin=process.env.NEXT_PUBLIC_SITE_URL||"http://localhost:3000";return`${origin}/notificaciones/baja?token=${encodeURIComponent(createUnsubscribeToken(userId))}`}

export async function sendWelcomeEmail(input:{userId:string;email:string;name:string}){const resend=getResend();const from=process.env.RESEND_FROM_EMAIL;if(!resend||!from)return{configured:false};const link=unsubscribeUrl(input.userId);const{error}=await resend.emails.send({from,to:input.email,subject:"Bienvenido al Inner Circle",html:`<div style="font-family:Arial;background:#09070b;color:#fff;padding:32px"><h1>La señal está activa.</h1><p>Hola ${escape(input.name)}, tu perfil IAMJOSHWA / AFTERLUV está listo.</p><p>Recibirás únicamente los avisos que elegiste.</p><p style="margin-top:32px"><a href="${link}" style="color:#d88cff">Cambiar preferencias o cancelar suscripción</a></p></div>`,headers:{"List-Unsubscribe":`<${link}>`}});if(error)throw error;return{configured:true}}

export async function sendBookingEmails(input:{folio:string;name:string;email:string;project:string;eventDate:string;city:string}){const resend=getResend();const from=process.env.RESEND_FROM_EMAIL;const admin=process.env.BOOKING_NOTIFICATION_EMAIL;if(!resend||!from)return{configured:false};const subject=`Solicitud de booking recibida — ${input.folio}`;await resend.emails.send({from,to:input.email,subject,html:`<div style="font-family:Arial;background:#09070b;color:#fff;padding:32px"><h1>Recibimos tu solicitud</h1><p>Hola ${escape(input.name)}, revisaremos la información y responderemos personalmente.</p><p><strong>Folio:</strong> ${escape(input.folio)}</p><p>${escape(input.project.toUpperCase())} · ${escape(input.city)} · ${escape(input.eventDate)}</p></div>`});if(admin)await resend.emails.send({from,to:admin,subject:`Nueva solicitud ${input.folio}`,html:`<p>Nueva solicitud de ${escape(input.name)} para ${escape(input.project)} en ${escape(input.city)}. Consulta el panel administrativo.</p>`});return{configured:true}}
