import { requireRole } from "@/lib/auth/require-role";
import { archivePageSection, restoreVersion, savePageSection } from "../actions";

const blocks = ["hero", "next_event", "next_release", "featured_set", "events", "biography", "gallery", "video", "testimonials", "newsletter", "booking", "social_links", "custom_cta"];
type Section = { id?: string; project?: string; block_type?: string; variant?: string; content?: Record<string, string>; position?: number; publication_status?: string };
type Asset = { id:string; display_name:string; mime_type:string };

export default async function HomepageEditor() {
  const { supabase, role } = await requireRole(["editor", "admin"]);
  const [{ data }, { data: versions }, { data: assets }] = await Promise.all([
    supabase.from("page_sections").select("*").eq("page_key", "home").order("position"),
    supabase.from("content_versions").select("id,entity_id,version,created_at").eq("entity_type", "page_sections").order("created_at", { ascending: false }).limit(20),
    supabase.from("media_assets").select("id,display_name,mime_type").eq("bucket","public-media").is("archived_at",null).or("mime_type.like.image/%,mime_type.like.video/%").order("display_name"),
  ]);
  return <><header className="admin-header"><div><span className="section-kicker">EDITOR POR BLOQUES</span><h1>Portada</h1><p>Edita, ordena, previsualiza y publica variantes que conservan el diseño.</p></div><a className="button secondary" href="/" target="_blank">Ver portada pública</a></header><section className="section-editor"><div className="admin-table">{data?.length ? data.map((section) => <SectionForm key={section.id} section={section as Section} assets={assets||[]}/>) : <div className="admin-empty"><h2>Sin bloques configurados.</h2><p>Crea el hero o cualquier sección inicial.</p></div>}</div><SectionForm assets={assets||[]}/></section>{role === "admin" && Boolean(versions?.length) && <details className="settings-card version-list"><summary>Historial y restauración</summary>{versions?.map((version) => <form action={restoreVersion} key={version.id}><input type="hidden" name="versionId" value={version.id}/><p>Bloque {version.entity_id.slice(0, 8)} · versión {version.version}<br/><small>{new Date(version.created_at).toLocaleString("es-MX")}</small></p><button className="button secondary">Restaurar</button></form>)}</details>}</>;
}

function SectionForm({ section, assets }: { section?: Section; assets:Asset[] }) {
  const content = section?.content || {};
  return <form action={savePageSection} className="settings-card"><input type="hidden" name="id" value={section?.id || ""}/><span>{section ? `EDITAR ${(section.block_type || "bloque").toUpperCase()}` : "NUEVO BLOQUE"}</span><label>Universo<select name="project" defaultValue={section?.project || "iamjoshwa"}><option value="iamjoshwa">IAMJOSHWA</option><option value="afterluv">AFTERLUV</option></select></label><label>Bloque<select name="blockType" defaultValue={section?.block_type || "hero"}>{blocks.map((block) => <option key={block}>{block}</option>)}</select></label><label>Variante<select name="variant" defaultValue={section?.variant || "default"}><option>default</option><option>split</option><option>immersive</option><option>compact</option></select></label><label>Título<input name="title" defaultValue={content.title || ""}/></label><label>Subtítulo<input name="subtitle" defaultValue={content.subtitle || ""}/></label><label>Texto<textarea name="body" rows={3} defaultValue={content.body || ""}/></label><label>Imagen o video<select name="mediaAssetId" defaultValue={content.media_asset_id||""}><option value="">Sin asignar</option>{assets.map(asset=><option value={asset.id} key={asset.id}>{asset.display_name} · {asset.mime_type.split("/")[0]}</option>)}</select></label><label>Texto del botón<input name="ctaLabel" defaultValue={content.cta_label || ""}/></label><label>Ruta del botón<input name="ctaHref" defaultValue={content.cta_href || ""}/></label><label>Posición<input name="position" type="number" min="0" defaultValue={section?.position || 0}/></label><label>Estado<select name="status" defaultValue={section?.publication_status || "draft"}><option value="draft">Borrador</option><option value="scheduled">Programado</option><option value="published">Publicado</option><option value="archived">Archivado</option></select></label><label>Fecha de publicación<input name="publishAt" type="datetime-local"/></label><div className="editor-actions"><button className="button primary">Guardar</button>{section?.id && <button className="button danger-button" formAction={archivePageSection}>Archivar</button>}</div></form>;
}
