"use server";
import{revalidatePath}from"next/cache";import QRCode from"qrcode";import{requireRole}from"@/lib/auth/require-role";import{createAdminClient}from"@/lib/supabase/admin";import{publicEnv}from"@/lib/env";
export async function updateBookingStatus(data:FormData){const{supabase,user}=await requireRole(["editor","admin"]);const id=String(data.get("id"));const status=String(data.get("status"));if(!["new","contacted","negotiating","confirmed","rejected","cancelled","completed"].includes(status))throw new Error("Estado inválido");const{data:old}=await supabase.from("booking_requests").select("status").eq("id",id).single();const{error}=await supabase.from("booking_requests").update({status}).eq("id",id);if(error)throw error;await supabase.from("audit_logs").insert({actor_id:user.id,action:"booking_status",entity_type:"booking_requests",entity_id:id,old_values:old,new_values:{status}});revalidatePath("/admin/booking")}
export type CheckinTokenState={ok?:boolean;message?:string;token?:string;url?:string;qr?:string;expiresAt?:string};
export async function createCheckinToken(_state:CheckinTokenState,data:FormData):Promise<CheckinTokenState>{const{supabase}=await requireRole(["editor","admin"]);try{const eventId=String(data.get("eventId"));const expiresAt=new Date(String(data.get("expiresAt"))).toISOString();const{data:result,error}=await supabase.rpc("create_checkin_token",{p_event_id:eventId,p_expires_at:expiresAt});if(error)throw error;const payload=result as {token?:string;expires_at?:string};if(!payload.token)throw new Error("No se pudo generar el token");const url=`${publicEnv.NEXT_PUBLIC_SITE_URL}/checkin?token=${encodeURIComponent(payload.token)}`;const qr=await QRCode.toDataURL(url,{margin:1,width:720,color:{dark:"#070609",light:"#ffffff"}});revalidatePath("/admin/checkins");return{ok:true,message:"QR generado. Usa esta pantalla para copiar o descargar el acceso.",token:payload.token,url,qr,expiresAt:payload.expires_at}}catch(error){return{ok:false,message:error instanceof Error?error.message:"No fue posible generar el QR"}}}
export async function disableCheckinToken(data:FormData){const{supabase}=await requireRole(["editor","admin"]);const tokenId=String(data.get("tokenId"));const{error}=await supabase.rpc("disable_checkin_token",{p_token_id:tokenId});if(error)throw error;revalidatePath("/admin/checkins")}
export async function grantManualPoints(data:FormData){const{user}=await requireRole(["admin"]);const target=String(data.get("userId"));const points=Number(data.get("points"));const reason=String(data.get("reason")||"").trim();if(!Number.isInteger(points)||points===0||Math.abs(points)>5000||reason.length<5)throw new Error("Movimiento inválido");const db=createAdminClient();const{error}=await db.from("points_ledger").insert({user_id:target,points,reason,source_type:"admin_adjustment",idempotency_key:`admin:${user.id}:${crypto.randomUUID()}`,created_by:user.id});if(error)throw error;await db.from("audit_logs").insert({actor_id:user.id,action:"points_adjustment",entity_type:"profiles",entity_id:target,new_values:{points,reason}});revalidatePath("/admin/puntos")}
export async function assignRole(data:FormData){const{user}=await requireRole(["admin"]);const target=String(data.get("userId"));const role=String(data.get("role"));if(!["fan","editor","admin"].includes(role)||target===user.id&&role!=="admin")throw new Error("Cambio de rol inválido");const db=createAdminClient();await db.from("user_roles").delete().eq("user_id",target);const{error}=await db.from("user_roles").insert({user_id:target,role,can_publish:data.get("canPublish")==="on"});if(error)throw error;await db.from("audit_logs").insert({actor_id:user.id,action:"role_change",entity_type:"user_roles",entity_id:target,new_values:{role}});revalidatePath("/admin/usuarios")}
export async function saveAvailability(data:FormData){const{supabase,user}=await requireRole(["editor","admin"]);const project=String(data.get("project"));const status=String(data.get("status"));const startsAt=new Date(String(data.get("startsAt")));const endsAt=new Date(String(data.get("endsAt")));if(!["iamjoshwa","afterluv"].includes(project)||!["available","hold","booked","unavailable"].includes(status)||Number.isNaN(startsAt.getTime())||Number.isNaN(endsAt.getTime())||endsAt<=startsAt)throw new Error("Disponibilidad inválida");const payload={project,status,starts_at:startsAt.toISOString(),ends_at:endsAt.toISOString(),notes:String(data.get("notes")||"").trim()||null};const{data:item,error}=await supabase.from("availability").insert(payload).select("id").single();if(error)throw error;await supabase.from("audit_logs").insert({actor_id:user.id,action:"create",entity_type:"availability",entity_id:item.id,new_values:payload});revalidatePath("/admin/disponibilidad")}
export async function deleteAvailability(data:FormData){const{supabase,user}=await requireRole(["editor","admin"]);const id=String(data.get("id"));const{data:old}=await supabase.from("availability").select("*").eq("id",id).single();if(!old)throw new Error("Registro no encontrado");const{error}=await supabase.from("availability").delete().eq("id",id);if(error)throw error;await supabase.from("audit_logs").insert({actor_id:user.id,action:"delete",entity_type:"availability",entity_id:id,old_values:old});revalidatePath("/admin/disponibilidad")}
