import {z} from "zod";
const empty=(value:unknown)=>value===""||value===null?undefined:value;
const url=z.preprocess(empty,z.string().url().refine(value=>/^https?:\/\//i.test(value),"Solo se permiten URLs HTTP o HTTPS").optional());
const date=z.preprocess(empty,z.string().datetime({offset:true}).optional());
const uuid=z.preprocess(empty,z.string().uuid().optional());
const project=z.enum(["iamjoshwa","afterluv"]);const publication=z.enum(["draft","scheduled","published","archived"]);const common={project,publication_status:publication,publish_at:date};
export const adminSchemas={
  eventos:z.object({...common,name:z.string().trim().min(2).max(160),slug:slug(),flyer_asset_id:uuid,starts_at:z.string().datetime({offset:true}),doors_at:date,set_starts_at:date,venue:text(180),address:text(300),city:z.string().trim().min(2).max(120),country:z.string().trim().min(2).max(120),latitude:z.number().min(-90).max(90).optional(),longitude:z.number().min(-180).max(180).optional(),lineup:list(50,100),genres:list(30,50),age_restriction:text(50),price_amount:z.number().nonnegative().optional(),currency:z.string().length(3).optional(),ticket_url:url,promo_code:text(50),description:text(10000),faq:z.array(z.object({question:z.string().min(1).max(300),answer:z.string().min(1).max(2000)})).max(30).default([]),event_status:z.enum(["upcoming","registration_open","presale","last_tickets","sold_out","waitlist","cancelled","rescheduled","completed"]).default("upcoming"),featured:z.boolean().default(false)}),
  lanzamientos:z.object({...common,name:z.string().trim().min(1).max(180),slug:slug(),cover_asset_id:uuid,preview_asset_id:uuid,release_type:z.string().trim().min(1).max(50),releases_at:z.string().datetime({offset:true}),story:text(10000),credits:z.array(z.object({role:z.string().min(1).max(100),name:z.string().min(1).max(150)})).max(50).default([]),presave_url:url,release_links:z.array(z.object({platform:z.string().min(1).max(50),url:z.string().url().refine(value=>/^https?:\/\//i.test(value)),position:z.number().int().nonnegative().default(0)})).max(20).default([]),featured:z.boolean().default(false)}),
  sets:z.object({...common,title:z.string().trim().min(1).max(180),slug:slug(),cover_asset_id:uuid,description:text(10000),recorded_at:z.preprocess(empty,z.string().date().optional()),location:text(180),duration_seconds:z.number().int().positive().optional(),genres:list(30,50),bpm_min:z.number().int().min(40).max(250).optional(),bpm_max:z.number().int().min(40).max(250).optional(),energy:z.number().int().min(1).max(5).optional(),category:text(80),soundcloud_url:url,youtube_url:url,mixcloud_url:url,external_url:url,access_level:z.enum(["public","exclusive"]).default("public"),set_tracks:z.array(z.object({position:z.number().int().positive(),timestamp_seconds:z.number().int().nonnegative().optional(),artist:z.string().max(150).optional(),title:z.string().min(1).max(200),is_unreleased:z.boolean().default(false)})).max(200).default([]),featured:z.boolean().default(false)}),
  historia:z.object({...common,title:z.string().trim().min(1).max(180),body:text(10000),occurred_at:z.preprocess(empty,z.string().date().optional()),asset_id:uuid,position:z.number().int().nonnegative().default(0)}),
  epk:z.object({...common,section_key:z.string().trim().regex(/^[a-z0-9_]+$/).max(80),content:z.record(z.string(),z.unknown()).default({}),position:z.number().int().nonnegative().default(0)}),
  recompensas:z.object({...common,name:z.string().trim().min(1).max(180),slug:slug(),description:text(5000),points_cost:z.number().int().nonnegative(),inventory:z.number().int().nonnegative().optional(),expires_at:date,requirements:z.record(z.string(),z.unknown()).default({})}),
  campanas:z.object({name:z.string().trim().min(2).max(180),channel:z.enum(["email","whatsapp","push"]),trigger_type:text(80),audience_filters:z.record(z.string(),z.unknown()).default({}),subject:text(200),template_key:z.string().trim().min(1).max(100),template_data:z.record(z.string(),z.unknown()).default({}),status:z.enum(["draft","scheduled","cancelled"]),scheduled_at:date}),
};
export type AdminModule=keyof typeof adminSchemas;
export function normalizeAdminValues(module:AdminModule,values:Record<string,unknown>){const normalized={...values};for(const key of["starts_at","doors_at","set_starts_at","releases_at","publish_at","expires_at","scheduled_at"]){if(typeof normalized[key]==="string"&&normalized[key]){const parsed=new Date(normalized[key] as string);normalized[key]=Number.isNaN(parsed.getTime())?"invalid-date":parsed.toISOString()}}for(const key of["price_amount","latitude","longitude","duration_seconds","bpm_min","bpm_max","energy","points_cost","inventory","position"]){if(normalized[key]!==""&&normalized[key]!=null)normalized[key]=Number(normalized[key]);else delete normalized[key]}normalized.featured=normalized.featured===true||normalized.featured==="on";for(const key of["lineup","genres"])if(typeof normalized[key]==="string")normalized[key]=(normalized[key] as string).split(",").map(x=>x.trim()).filter(Boolean);for(const key of["faq","credits","release_links","set_tracks","content","requirements","audience_filters","template_data"])if(typeof normalized[key]==="string"){try{normalized[key]=JSON.parse(normalized[key] as string)}catch{normalized[key]=null}}return adminSchemas[module].safeParse(normalized)}
function slug(){return z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)}function text(max:number){return z.preprocess(empty,z.string().trim().max(max).optional())}function list(maxItems:number,maxLength:number){return z.array(z.string().max(maxLength)).max(maxItems).default([])}
