import { notFound } from "next/navigation";
import Link from "next/link";
import { requireRole } from "@/lib/auth/require-role";
import { CheckinTokenManager } from "@/components/admin/checkin-token-manager";
import { assignRole, deleteAvailability, grantManualPoints, saveAvailability, updateBookingStatus } from "../module-actions";

const definitions:Record<string,{title:string;description:string;table?:string}>={eventos:{title:"Eventos",description:"Fechas, boletos, estados, FAQ y check-in.",table:"events"},lanzamientos:{title:"Lanzamientos",description:"Pre-saves, plataformas, créditos y programación.",table:"releases"},sets:{title:"Sets",description:"Biblioteca, tracklists, embeds y acceso exclusivo.",table:"sets"},historia:{title:"Historia",description:"Biografía y línea de tiempo artística.",table:"artist_timeline"},epk:{title:"EPK",description:"Material profesional, riders y descargas.",table:"epk_content"},booking:{title:"Booking",description:"Solicitudes y seguimiento comercial.",table:"booking_requests"},disponibilidad:{title:"Disponibilidad",description:"Holds, fechas libres y contrataciones.",table:"availability"},usuarios:{title:"Usuarios",description:"Perfiles, roles y consentimiento.",table:"profiles"},comunidad:{title:"Comunidad",description:"Ciudades, preferencias y actividad.",table:"profiles"},puntos:{title:"Ledger de puntos",description:"Movimientos inmutables otorgados por servidor.",table:"points_ledger"},insignias:{title:"Insignias",description:"Catálogo y asignaciones verificadas.",table:"badges"},checkins:{title:"Check-ins",description:"Asistencia QR, vigencia y recompensas.",table:"event_checkins"},referidos:{title:"Referidos",description:"Invitaciones, validación y recompensas.",table:"referrals"},recompensas:{title:"Recompensas",description:"Inventario, costos y canjes.",table:"rewards"},campanas:{title:"Campañas",description:"Email, audiencias, programación y entregas.",table:"campaigns"}};
const editable=new Set(["eventos","lanzamientos","sets","historia","epk","recompensas","campanas"]);

export default async function AdminModule({params}:{params:Promise<{module:string}>}){
  const{module}=await params;const def=definitions[module];if(!def)notFound();
  const{supabase,role}=await requireRole(["editor","admin"]);
  let rows:Record<string,unknown>[]=[];
  if(def.table){const result=await supabase.from(def.table).select("*").order("created_at",{ascending:false}).limit(100);rows=result.data||[]}
  const{data:events}=module==="checkins"?await supabase.from("events").select("id,name").eq("publication_status","published").order("starts_at"):{data:null};
  const{data:tokens}=module==="checkins"?await supabase.from("event_checkin_tokens").select("id,event_id,active,expires_at,created_at,revoked_at,events(name)").order("created_at",{ascending:false}).limit(20):{data:null};
  return <><header className="admin-header"><div><span className="section-kicker">CMS</span><h1>{def.title}</h1><p>{def.description}</p></div>{editable.has(module)&&<Link className="button primary" href={`/admin/${module}/nuevo`}>Nuevo</Link>}</header>
  {module==="disponibilidad"&&<form action={saveAvailability} className="settings-card inline-admin-form"><label>Proyecto<select name="project"><option value="iamjoshwa">IAMJOSHWA</option><option value="afterluv">AFTERLUV</option></select></label><label>Desde<input name="startsAt" type="datetime-local" required/></label><label>Hasta<input name="endsAt" type="datetime-local" required/></label><label>Estado<select name="status"><option value="available">Disponible</option><option value="hold">Hold</option><option value="booked">Contratado</option><option value="unavailable">No disponible</option></select></label><label>Notas<input name="notes"/></label><button className="button primary">Agregar disponibilidad</button></form>}
  {module==="checkins"&&<CheckinTokenManager events={events||[]} tokens={(tokens||[]) as never}/>}
  {module==="puntos"&&role==="admin"&&<form action={grantManualPoints} className="settings-card inline-admin-form"><label>ID del usuario<input name="userId" required/></label><label>Puntos<input name="points" type="number" required/></label><label>Motivo<input name="reason" minLength={5} required/></label><button className="button primary">Registrar movimiento</button></form>}
  {module==="usuarios"&&role==="admin"&&<form action={assignRole} className="settings-card inline-admin-form"><label>ID del usuario<input name="userId" required/></label><label>Rol<select name="role"><option value="fan">Fan</option><option value="editor">Editor</option><option value="admin">Admin</option></select></label><label className="checkbox"><input name="canPublish" type="checkbox"/>Puede publicar</label><button className="button primary">Actualizar rol</button></form>}
  <section className="admin-table"><div className="admin-table-head"><span>REGISTROS</span><span>{rows.length} resultados</span></div>{rows.length===0?<div className="admin-empty"><h2>Aún no hay contenido.</h2><p>{editable.has(module)?"Usa “Nuevo” para crear el primer registro. Nada se publicará sin revisión.":"Los registros aparecerán cuando exista actividad."}</p></div>:rows.map((row,index)=><article key={String(row.id||index)}><div><strong>{String(row.name||row.title||row.folio||row.slug||row.display_name||row.project||"Registro")}</strong><small>{row.starts_at?new Date(String(row.starts_at)).toLocaleString("es-MX"):String(row.status||row.publication_status||row.created_at||"")}</small></div>{module==="booking"?<div className="inline-actions"><form action={updateBookingStatus}><input type="hidden" name="id" value={String(row.id)}/><select name="status" defaultValue={String(row.status)}><option value="new">Nueva</option><option value="contacted">Contactado</option><option value="negotiating">En negociación</option><option value="confirmed">Confirmada</option><option value="rejected">Rechazada</option><option value="cancelled">Cancelada</option><option value="completed">Finalizada</option></select><button className="button secondary">Guardar</button></form><Link className="button secondary" href={`/admin/booking/${row.id}`}>Ver solicitud</Link></div>:module==="disponibilidad"?<form action={deleteAvailability}><input type="hidden" name="id" value={String(row.id)}/><button className="button danger-button">Eliminar</button></form>:editable.has(module)&&<Link className="button secondary" href={`/admin/${module}/${row.id}`}>Editar</Link>}</article>)}</section></>;
}
